import Head from "next/head";
import React from "react";
import MyProjectsModule from "@modules/MyProject/MyProjectsModule";
import { certData } from "../../styles/data/cert-data";
import { myProjectData } from "../../styles/data/myproject-data";

export default function MyProjectsPage() {
  return (
    <>
      <Head>
        <title>My Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyProjectsModule data={myProjectData} />
    </>
  );
}
