version: "3"
services:
  nginx:
    image: nginx:1.23.0-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx-selfsigned.crt:/etc/nginx/nginx-selfsigned.crt
      - ./nginx/nginx-selfsigned.key:/etc/nginx/nginx-selfsigned.key
    ports:
      - 80:80
      - 443:443
    networks:
      - app-network
  app:
    image: myweb:latest
    container_name: myweb
    restart: unless-stopped
    tty: true
    ports:
      - "3000:3000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
    name: app-network
