version: "3.8"
services:
  nginx:
    image: nginx:1.23.0-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - network-web

  app-web:
    image: hustlerxiv/my-web
    build: ./
    container_name: app-web
    working_dir: /myweb/
    tty: true
    ports:
      - 3000:3000
    networks:
      - network-web
networks:
  network-web:
    name: network-web
    driver: bridge
