import Head from "next/head";
import Image from "next/image";
import HomaPageModule from "../modules/HomePage/HomaPageModule";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomaPageModule />
    </>
  );
}
