import Head from "next/head";
import HomaPageModule from "@modules/HomePage/HomaPageModule";
import { myProjectData } from "../styles/data/myproject-data";

export default function Home() {
  const projectData = myProjectData.filter((i) => i.principal === true);
  return (
    <>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomaPageModule projectData={projectData} />
    </>
  );
}
